# Generated by Django 4.2.7 on 2025-09-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload brand/technology logo image', null=True, upload_to='skills/'),
        ),
    ]
