# Generated by Django 4.2.7 on 2025-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=50, help_text='Proficiency level from 0-100%'),
        ),
    ]
